# Generated by Django 2.2.5 on 2020-06-13 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITSM_User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('login', models.CharField(max_length=61, primary_key=True, serialize=False, unique=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('surname', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=30, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_change_date', models.DateTimeField(auto_now=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=40, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_operator', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('code_name', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset_type',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business_unit',
            fields=[
                ('name', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field_type',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('name', models.CharField(max_length=1, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('value', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('time_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=1024)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('resume_date', models.DateTimeField(blank=True, null=True)),
                ('last_change_date', models.DateTimeField(auto_now=True)),
                ('asset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itsm.Asset')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sr_author_id', to=settings.AUTH_USER_MODEL)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itsm.Business_unit')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itsm.Classification')),
                ('owner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sr_owner_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_type',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work_journal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_title', models.CharField(max_length=60)),
                ('record_description', models.CharField(max_length=1024)),
                ('is_internal', models.BooleanField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_author_id', to=settings.AUTH_USER_MODEL)),
                ('service_request_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itsm.Service_request')),
            ],
        ),
        migrations.CreateModel(
            name='Sr_pattern',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itsm.Classification')),
            ],
        ),
        migrations.AddField(
            model_name='service_request',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itsm.Sr_pattern'),
        ),
        migrations.AddField(
            model_name='service_request',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itsm.Priority'),
        ),
        migrations.AddField(
            model_name='service_request',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itsm.Status'),
        ),
        migrations.CreateModel(
            name='Pattern_row',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_required', models.BooleanField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itsm.Sr_pattern')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itsm.Field_type')),
            ],
        ),
        migrations.CreateModel(
            name='Communication_journal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_title', models.CharField(max_length=255)),
                ('record_description', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_internal', models.BooleanField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_author_id', to=settings.AUTH_USER_MODEL)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_receiver_id', to=settings.AUTH_USER_MODEL)),
                ('service_request_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itsm.Service_request')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itsm.Asset_type'),
        ),
        migrations.AddField(
            model_name='asset',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itsm.Business_unit'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_change_author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_last_change_author_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_person_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itsm.AssetStatus'),
        ),
        migrations.AddField(
            model_name='itsm_user',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itsm.Business_unit'),
        ),
        migrations.AddField(
            model_name='itsm_user',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itsm.Gender'),
        ),
        migrations.AddField(
            model_name='itsm_user',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itsm.Name'),
        ),
        migrations.AddField(
            model_name='itsm_user',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itsm.User_type'),
        ),
    ]
